use_isochron_interp = true
model_name = "zahirovic2022"
times = [0, 50, 100, 150]

# The input files can be found at https://repo.gplates.org/webdav/gplately/AgeGridInput.zip.
ridges_filenames = "AgeGridInput/Global_EarthByte_GeeK07_Ridges.gpml"
isochron_filenames = "AgeGridInput/Global_EarthByte_GeeK07_Isochrons.gpml"
isochron_cob_filenames = "AgeGridInput/Global_EarthByte_GeeK07_IsoCOB.gpml"
continents_filenames = ["AgeGridInput/Global_EarthByte_GeeK07_COB_Terranes_ContinentsOnly.gpml"]
interval_spacing = 0.5
grid_spacing = 0.5	