version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  gplatelylog:
    class: logging.FileHandler
    level: WARNING
    formatter: simple
    filename: gplately.log
    mode: a

  pttlog:
    class: logging.FileHandler
    level: WARNING
    formatter: simple
    filename: ptt.log
    mode: a

loggers:
  gplately:
    level: WARNING
    handlers: [console, gplatelylog]
    propagate: no

  ptt:
    level: WARNING
    handlers: [console, pttlog]
    propagate: no

root:
  level: WARNING
  handlers: [console, gplatelylog, pttlog]
