# Note: This will go into the 'recipe' directory of
#       https://github.com/conda-forge/gplately-feedstock
#       in order to use pygplates-1.0.0rc1 (which is in a different channel).
#       Although probably won't be necessary to add (to feedstock) because pygplates-1.0.0
#       (main channel) will be out soon (Jan 2025), and GPlately 2.0 can just use that.
channel_sources:
  - conda-forge/label/pygplates_rc,conda-forge
