{% set name = "gplately" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - numpy >=1.16.0
    - scipy >=1.0.0
    - pygplates
    - shapely
    - matplotlib-base
    - cartopy
    - platetectonictools
    - pooch
    - tqdm
    - netcdf4
    - rasterio
    - geopandas
    - stripy
    - pykdtree

test:
  imports:
    - gplately
  commands:
    - pip check
  requires:
    - pip
    - pytest

about:
  home: https://github.com/GPlates/gplately
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Object-orientated Python interface to pyGPlates for plate tectonic reconstructions

extra:
  recipe-maintainers:
    - brmather
    - jcannon-gplates
