# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test GPlately

on:
  push:

jobs:
  build:

    name: Test Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: actions/checkout@v2
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.3.1-0'
          environment-file: test/test-env.yml
          init-shell: >-
            bash
            powershell
          cache-environment: true
          post-cleanup: 'all' 
      - run: conda info
      - run: conda list
      - run: conda config --show

      - name: Install gplately and dependencies
        run: |
          mamba install gplately pytest

      - name: Install current gplately
        run: |
          pip install . --no-binary :all: --no-cache-dir --no-dependencies

      - name: Test with pytest
        run: |
          python -m pytest -vv
