# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test GPlately

on:
  push:


jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -yq python3-dev wget libboost-python-dev libboost-program-options-dev libgdal-dev libglew-dev libglu1-mesa libproj-dev libqt5core5a libqt5gui5 libqt5network5 libqt5opengl5 libqt5svg5 libqt5widgets5 libqt5xml5 libqt5xmlpatterns5 libqwt-qt5-6
        wget https://bootstrap.pypa.io/get-pip.py
        python3 get-pip.py
        wget https://cloudstor.aarnet.edu.au/plus/s/TKNCRHjlWzfa4Bh/download -O pygplates_package.deb
        yes | sudo dpkg -i pygplates_package.deb
    - name: Install gplately
      run: |
        pip install .
    - name: Test with pytest
      run: |
        export PYTHONPATH=$PYTHONPATH:/usr/lib/
        pytest
