# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test GPlately

on:
  push:

jobs:
  build:

    name: Test Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: test

      - name: Install gplately and dependencies
        run: |
          conda activate test
          mamba install gplately pytest

      - name: Install current gplately
        run: |
          conda activate test
          pip install . --no-binary :all: --no-cache-dir --no-dependencies

      - name: Test with pytest
        run: |
          conda activate test
          pytest -vv
