# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test GPlately

on:
  push:
    branches:
      - master
    paths:
      - gplately/**
  pull_request:
    branches:
      - master
    paths:
      - gplately/**

jobs:
  build:
    name: Test Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # Conda-forge currently supports Python >=3.10 ...
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    defaults:
      run:
        shell: bash -el {0}
        
    if: github.event.pull_request.draft == false
    steps:
      # Used with 'cache-environment-key'.
      # See https://github.com/mamba-org/setup-micromamba?tab=readme-ov-file#caching
      - name: Get current date
        id: date
        run: echo "date=$(date +%Y-%m-%d)" >> "${GITHUB_OUTPUT}"
      
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: "1.5.8-0"
          environment-file: tests-dir/test-env.yml
          create-args: >-
            python=${{ matrix.python-version }}
          init-shell: >-
            bash
            powershell
          cache-environment: true
          # Cache only on the same day.
          # See https://github.com/mamba-org/setup-micromamba?tab=readme-ov-file#caching
          cache-environment-key: environment-${{ steps.date.outputs.date }}
          post-cleanup: "all"

      - name: Install current gplately
        run: |
          pip install . --no-binary :all: --no-cache-dir --no-dependencies

      - name: Set SSL cert path (Windows workaround)
        # This is a workaround for SSL certificate issues on Windows runners.
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $certPath = python -c "import certifi; print(certifi.where())"
          echo "SSL_CERT_FILE=$certPath" >> $env:GITHUB_ENV

      - name: Test with pytest
        run: |
          python -m pytest -vv tests-dir/pytestcases
