# This workflow is triggered when a release is published. It creates the "latest" tag for the Docker images 
# on Docker Hub and GitHub Container Registry (ghcr.io) for both amd64 and arm64 architectures.

name: Create Docker Latest Tag on Publishing Release

on:
  release:
    types: [published]

jobs:
  create-docker-latest-tag:
    name: Create Docker Latest Tag on Publishing Release
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Decide the Docker Image Version Number
        run: |
            echo "DOCKER_IMAGE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
            echo ${{ env.DOCKER_IMAGE_TAG }}
      -
        name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -     
        name: Create the Latest Tags
        run: |
          docker buildx imagetools create -t gplates/gplately:latest gplates/gplately:amd64-${{ env.DOCKER_IMAGE_TAG }} gplates/gplately:arm64-${{ env.DOCKER_IMAGE_TAG }}
          docker buildx imagetools create -t ghcr.io/gplates/gplately:latest ghcr.io/gplates/gplately:amd64-${{ env.DOCKER_IMAGE_TAG }} ghcr.io/gplates/gplately:arm64-${{ env.DOCKER_IMAGE_TAG }} 

