name: Build docs and deploy to GitHub Pages

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: "1.5.8-0"
          environment-file: conda/doc-env.yml
          init-shell: >-
            bash
          cache-environment: true
          post-cleanup: "all"

      - name: Install current gplately
        run: |
          pip install . --no-binary :all: --no-cache-dir --no-dependencies

      - name: Generate documentation with pdoc3
        run: |
          pdoc3 --config latex_math=True --template-dir .pdoc_template --html -o api --force gplately
      
      - name: Convert jupyter notebooks to html
        run: |
          jupyter-nbconvert --to=html --output-dir=api/gplately/ Notebooks/*.ipynb
          
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: api/gplately/
          target-folder: dev-doc/
