# This workflow will upload GPlately Python Package using Twine when a release is published.

name: Upload GPlately Python Package to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  upload-to-pypi:
    name: Upload GPlately Python Package to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish package
        run: |
          chmod +x ./scripts/pypi-publish.sh
          ./scripts/pypi-publish.sh '${{secrets.PYPI_API_TOKEN}}'
